FACILITATOR_MEMO_TYPE: str
FACILITATOR_MEMO_FORMAT: str

def text_to_memo_hex(text: str) -> str: ...
def invoice_id_to_memo_hex(invoice_id: str) -> str: ...
def invoice_id_to_invoice_id_field(invoice_id: str) -> str: ...
def to_currency_hex(code: str) -> str: ...
